debug:
  dump-urls: True
  log-stack-traces: True

server:
  port: 8000

request-matching:
  rules:
    - method
    - path
    - query-params
    - headers

rewrite-rules:
  response:
    - localhost
    - remove-headers
  request:
    - remove-query-params
    - remove-headers
  config:
    excluded-domains:
      - http://www.w3.org
    removable-query-params:
      - w
      - q
    removable-response-headers:
      - content-type
      - content-encoding
    removable-request-headers:
      - Accept

entry-exclusions:
  rules:
    - responses-with-bad-status
    - responses-with-invalid-size
    - duplicate-requests
  config:
    bad-statuses:
      - 0
      - 304