debug:
  dump-urls: True
  log-stack-traces: True
  enable-debug-logs: True

server:
  port: 8080
  open: http://localhost:${server.port}/

request-matching:
  rules:
    - method
    - path
    - query-params
    - headers

rewrite-rules:
  response:
    - urls-in-response
    - remove-headers
  request:
    - remove-query-params
    - remove-headers
    - remove-cookies
  config:
    excluded-domains:
      - http://www.w3.org
    removable-cookies:
      - SESSIONID
    removable-query-params:
      - w
      - q
    removable-response-headers:
      - content-type
      - content-encoding
    removable-request-headers:
      - Accept

entry-exclusions:
  rules:
    - responses-with-status
    - responses-with-invalid-size
    - duplicate-requests
  config:
    removable-statuses:
      - 0
      - 304