debug:
  enable-debug-logs: True
  log-stack-traces: True
  open-browser: http://localhost:8080/

request-matching:
  rules:
    - method
    - path
    - query-params
    - headers
    - cookies
    - json-body

rewrite:
  request:
    rules:
      - remove-query-params
      - remove-headers
      - remove-cookies
    config:
      pre-apply: True
      removable-headers:
        - content-type
        - content-length
        - content-encoding
      removable-cookies:
        - SESSIONID
      removable-query-params:
        - t
        - time
        - r
  response:
    rules:
      - urls-in-response
      - remove-headers
      - remove-cookies
    config:
      excluded-domains:
        - http://w3.com/
      removable-headers:
        - content-type
        - content-length
        - content-encoding
      removable-cookies:
        - SESSIONID

exclusions:
  rules:
    - responses-with-status
    - responses-with-invalid-size
    - requests-with-http-method
  config:
    pre-apply: True
    removable-http-methods:
      - HEAD
    removable-statuses:
      - 0
      - 304
      - 500