port: 8080
open-browser: http://localhost:{port}/

debug:
  enable-debug-logs: False
  log-stack-traces: True

request-matching:
  rules:
    - method
    - path
    - query-params
    - headers
    - cookies
    - body

rewrite:
  request:
    rules:
      - remove-query-params
      - remove-headers
      - remove-cookies
    config:
      removable-headers:
        - content-type
        - content-length
        - content-encoding
      removable-cookies:
        - SESSIONID
      removable-query-params:
        - t
        - time
        - r
  response:
    rules:
      - urls-in-response
      - remove-headers
      - remove-cookies
      - remove-html-script-tags
      - remove-integrity-attribute
    config:
      excluded-domains:
        - http://w3.com/
      removable-headers:
        - content-type
        - content-length
        - content-encoding
      removable-cookies:
        - SESSIONID

exclusions:
  rules:
    - responses-with-status
    - responses-with-invalid-size
    - requests-with-http-method
    - requests-with-matching-url
  config:
    removable-url-expressions:
      - ^https:\/\/www\.youtube\.com\/embed\/.*
    removable-http-methods:
      - HEAD
    removable-statuses:
      - 0
      - 304
      - 500